// Real YWEE product catalog — generated from Amazon data
// Girls Denim Jeans, Ages 1-14, Made in India

export interface Product {
  id: string;
  asin: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  images: string[];
  category: string;
  ageCategory: string;
  sizes: string[];
  colors: string[];
  badge?: string;
  rating: number;
  reviews: number;
  description: string;
  material: string;
  pattern: string;
  colour: string;
  riseStyle: string;
  ageRange: string;
  inStock: boolean;
}

export const CATEGORIES = [
  { id: "all", label: "All Styles", ageRange: "Ages 1-14", image: "/manus-storage/ywee-collection-banner1.png", video: "" },
  { id: "dark-blue", label: "Dark Blue", ageRange: "Classic Denim", image: "/manus-storage/ywee-enhanced-floral-dark.png", video: "" },
  { id: "light-blue", label: "Light Blue", ageRange: "Soft & Sweet", image: "/manus-storage/ywee-enhanced-light-blue.png", video: "" },
  { id: "black", label: "Black", ageRange: "Bold & Cool", image: "/manus-storage/ywee-enhanced-black-love.png", video: "" },
  { id: "toddler", label: "Toddler", ageRange: "Ages 1-4", image: "/manus-storage/ywee-collection-banner3.png", video: "" },
  { id: "little-girls", label: "Little Girls", ageRange: "Ages 4-8", image: "/manus-storage/ywee-collection-banner2.png", video: "" },
  { id: "big-girls", label: "Big Girls", ageRange: "Ages 8-14", image: "/manus-storage/ywee-enhanced-dark-solid.png", video: "" },
] as const;

export const TESTIMONIALS = [
  { name: "Priya M.", location: "Mumbai", text: "My daughter absolutely loves her YWEE jeans! The stretch fabric is perfect — she can run, jump, and play without any restrictions. The floral print is so cute!", rating: 5, avatar: "PM" },
  { name: "Sunita K.", location: "Delhi", text: "Finally found jeans that fit my toddler perfectly. The adjustable waistband is a lifesaver. Ordered 3 pairs already!", rating: 5, avatar: "SK" },
  { name: "Ananya R.", location: "Bangalore", text: "The quality is amazing for the price. My 10-year-old refuses to wear anything else now. The dark blue ones are her favourite!", rating: 5, avatar: "AR" },
  { name: "Deepika S.", location: "Chennai", text: "Love the cartoon prints! My daughter gets so many compliments at school. Fast delivery and great packaging too.", rating: 5, avatar: "DS" },
  { name: "Meera T.", location: "Pune", text: "Bought the black jeans with the Love More print — absolutely stunning. The cotton-lycra blend is so soft and comfortable.", rating: 5, avatar: "MT" },
] as const;

export const FAQS = [
  { q: "What sizes are available?", a: "YWEE jeans are available for girls aged 1 to 14 years. Each product listing shows the specific age/size it fits. We recommend checking the age range in the product description for the perfect fit." },
  { q: "What material are YWEE jeans made from?", a: "All YWEE jeans are crafted from premium Cotton-Lycra (cotton with elastane/spandex blend). This gives them the perfect stretch for active kids while maintaining their shape wash after wash." },
  { q: "How do I care for YWEE jeans?", a: "Machine wash cold with similar colors. Tumble dry low or hang to dry. Do not bleach. Iron on low heat if needed. The cotton-lycra blend is designed to be durable and easy to care for." },
  { q: "Are YWEE jeans true to size?", a: "YWEE jeans are sized by age range. For the best fit, refer to the age range specified in each product. If your child is between sizes, we recommend sizing up for comfort and room to grow." },
  { q: "Where are YWEE jeans made?", a: "YWEE jeans are proudly Made in India by GENERATIONS CLOTHING LLP. We believe in quality Indian craftsmanship and use premium fabrics sourced locally." },
  { q: "Do you offer returns or exchanges?", a: "Yes! We offer hassle-free returns within 7 days of delivery. If the size doesn't fit or you're not satisfied, contact us and we'll make it right." },
] as const;

export function formatINR(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    asin: "B0FL2XB7Q5",
    name: "Black Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/ywee-enhanced-black-love.png",
    images: ["/manus-storage/ywee-enhanced-black-love.png", "/manus-storage/418-ofvxDvL.jpg", "/manus-storage/418-ofvxDvL.jpg"],
    category: "black",
    ageCategory: "little-girls",
    sizes: ["4-5", "6-7"],
    colors: ["Black"],
    badge: "New In",
    rating: 4.5,
    reviews: 0,
    description: "Classic black stretch denim jeans with a modern fit. The Cotton Lycra blend provides the perfect stretch for active girls who love to move.",
    material: "Cotton",
    pattern: "Solid",
    colour: "Black",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p2",
    asin: "B0FL2X7BKK",
    name: "Black Stretch Denim Jeans",
    price: 1499,
    image: "/manus-storage/41sJLJCBAnL.jpg",
    images: ["/manus-storage/41sJLJCBAnL.jpg", "/manus-storage/41sJLJCBAnL.jpg"],
    category: "black",
    ageCategory: "big-girls",
    sizes: ["12-13", "5-6"],
    colors: ["Black"],
    badge: "New In",
    rating: 4.5,
    reviews: 0,
    description: "Sleek and stylish, these black stretch denim jeans are a must-have for every girl's wardrobe. Premium Cotton Lycra blend for comfort that lasts.",
    material: "Cotton",
    pattern: "Solid",
    colour: "Black",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p3",
    asin: "B0FLDYQKVB",
    name: "Blue Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/6116arls0pL.jpg",
    images: ["/manus-storage/6116arls0pL.jpg", "/manus-storage/51-bnf5KgBL.jpg", "/manus-storage/51-bnf5KgBL.jpg", "/manus-storage/6116arls0pL.jpg", "/manus-storage/6116arls0pL.jpg"],
    category: "jeans",
    ageCategory: "big-girls",
    sizes: ["1-2", "10-11", "11-12", "2-3", "3-4", "4-5", "5-6", "7-8"],
    colors: ["Blue"],
    badge: "New In",
    rating: 4.5,
    reviews: 0,
    description: "Versatile blue stretch denim jeans perfect for school, play, and everything in between. Premium Cotton Lycra for all-day comfort.",
    material: "Denim",
    pattern: "Solid",
    colour: "Blue",
    riseStyle: "High Rise",
    ageRange: "Baby",
    inStock: true,
  },
  {
    id: "p4",
    asin: "B0FLDZJY88",
    name: "Dark Blue Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1599,
    image: "/manus-storage/51MCbXt6_ML.jpg",
    images: ["/manus-storage/51MCbXt6_ML.jpg", "/manus-storage/51HfmeylFiL.jpg", "/manus-storage/51GOrHPmxUL.jpg", "/manus-storage/61UP28St7ML.jpg", "/manus-storage/515fZg_d2EL.jpg"],
    category: "dark-blue",
    ageCategory: "big-girls",
    sizes: ["10-11", "12-13", "3-4", "4-5", "6-7", "7-8", "9-10"],
    colors: ["Dark Blue"],
    badge: "New In",
    rating: 4.5,
    reviews: 0,
    description: "Premium dark blue stretch denim jeans crafted for active girls. The Cotton Lycra blend provides the perfect balance of structure and stretch for all-day wear.",
    material: "Cotton",
    pattern: "Solid",
    colour: "Dark Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p5",
    asin: "B0FL16RYN5",
    name: "Dark Blue Cartoon Print Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/ywee-enhanced-light-blue.png",
    images: ["/manus-storage/ywee-enhanced-light-blue.png", "/manus-storage/51wpwYNp15L.jpg", "/manus-storage/51anNpeIzDL.jpg", "/manus-storage/51g_MHxOKNL.jpg", "/manus-storage/51DL0zh-0eL.jpg"],
    category: "dark-blue",
    ageCategory: "big-girls",
    sizes: ["10-11", "11-12", "7-8", "8-9", "9-10"],
    colors: ["Dark Blue"],
    badge: "New In",
    rating: 4.5,
    reviews: 0,
    description: "Fun meets fashion! These dark blue stretch denim jeans are adorned with adorable cartoon character prints that kids absolutely love. Super stretchy Cotton Lycra fabric moves with your little one.",
    material: "Cotton",
    pattern: "Cartoon",
    colour: "Dark Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p6",
    asin: "B0FL2XM93X",
    name: "Dark Blue Floral Print Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/ywee-enhanced-floral-dark.png",
    images: ["/manus-storage/ywee-enhanced-floral-dark.png", "/manus-storage/51kCW7HWx_L.jpg", "/manus-storage/61WA82eD_DL.jpg"],
    category: "dark-blue",
    ageCategory: "big-girls",
    sizes: ["11-12", "7-8"],
    colors: ["Dark Blue"],
    badge: "New In",
    rating: 4.5,
    reviews: 0,
    description: "Blooming with personality! These dark blue stretch denim flared jeans feature playful sunflower and daisy prints that make every step a statement. Crafted from soft Cotton Lycra for all-day comfort and stretch.",
    material: "Cotton",
    pattern: "Floral",
    colour: "Dark Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p7",
    asin: "B0FKYL7KWP",
    name: "Dark Blue Graphic Print Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/61DJ_p4AjcL.jpg",
    images: ["/manus-storage/61DJ_p4AjcL.jpg", "/manus-storage/61DJ_p4AjcL.jpg"],
    category: "dark-blue",
    ageCategory: "big-girls",
    sizes: ["7-8", "8-9"],
    colors: ["Dark Blue"],
    rating: 4.5,
    reviews: 0,
    description: "Bold and expressive! These dark blue stretch denim jeans feature fun graphic letter prints. Made from premium Cotton Lycra for a perfect fit that lasts all day.",
    material: "Cotton",
    pattern: "Letter Print",
    colour: "Dark Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p8",
    asin: "B0FKTHD1MT",
    name: "Dark Blue Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/ywee-enhanced-dark-solid.png",
    images: ["/manus-storage/ywee-enhanced-dark-solid.png", "/manus-storage/51qlc0PdAUL.jpg", "/manus-storage/51h0NYrlNCL.jpg", "/manus-storage/518hjIVOMpL.jpg", "/manus-storage/51Jms-_whoL.jpg"],
    category: "dark-blue",
    ageCategory: "big-girls",
    sizes: ["1-2", "10-11", "11-12", "12-13", "2-3", "3-4", "4-5", "5-6", "7-8", "8-9", "9-10"],
    colors: ["Dark Blue"],
    rating: 4.5,
    reviews: 0,
    description: "The ultimate everyday essential. These dark blue stretch denim jeans in a clean classic cut are crafted from premium Cotton Lycra for comfort and style from morning to night.",
    material: "Cotton",
    pattern: "Solid",
    colour: "Dark Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p9",
    asin: "B0FL16ZFCH",
    name: "Light Blue Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/51K6albn2KL.jpg",
    images: ["/manus-storage/51K6albn2KL.jpg", "/manus-storage/51P-fvBrfuL.jpg", "/manus-storage/51qv8EWVI3L.jpg", "/manus-storage/616qdUCYojL.jpg", "/manus-storage/61X_aeqzuFL.jpg"],
    category: "light-blue",
    ageCategory: "big-girls",
    sizes: ["10-11", "11-12", "3-4", "4-5", "5-6", "8-9", "9-10"],
    colors: ["Light Blue"],
    rating: 4.5,
    reviews: 0,
    description: "Soft light blue stretch denim jeans perfect for everyday adventures. The Cotton Lycra blend ensures comfort and flexibility for active girls.",
    material: "Cotton",
    pattern: "Solid",
    colour: "Light Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p10",
    asin: "B0FL15KNN2",
    name: "Light Blue Cartoon Print Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1599,
    image: "/manus-storage/51wXqX3-h7L.jpg",
    images: ["/manus-storage/51wXqX3-h7L.jpg", "/manus-storage/61028pNo7BL.jpg", "/manus-storage/51OsnfDS6qL.jpg", "/manus-storage/51wXqX3-h7L.jpg", "/manus-storage/51mOnx_Hn_L.jpg"],
    category: "light-blue",
    ageCategory: "big-girls",
    sizes: ["1-2", "10-11", "3-4", "5-6", "6-7", "7-8"],
    colors: ["Light Blue"],
    badge: "Trending",
    rating: 4.5,
    reviews: 0,
    description: "Playful and pretty! These light blue stretch denim jeans feature sweet cartoon prints that little girls adore. The soft Cotton Lycra fabric is gentle on skin and moves freely.",
    material: "Cotton",
    pattern: "Cartoon",
    colour: "Light Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
  {
    id: "p11",
    asin: "B0FL1481GP",
    name: "Light Blue Stretch Denim Jeans",
    price: 1399,
    originalPrice: 1499,
    image: "/manus-storage/51h0NYrlNCL.jpg",
    images: ["/manus-storage/51h0NYrlNCL.jpg", "/manus-storage/51E964heccL.jpg", "/manus-storage/41MAcqEpXWL.jpg", "/manus-storage/41L5YDiJIcL.jpg", "/manus-storage/41Zj766u_HL.jpg"],
    category: "light-blue",
    ageCategory: "big-girls",
    sizes: ["1-2", "10-11", "11-12", "12-13", "2-3", "3-4", "5-6", "7-8", "8-9", "9-10"],
    colors: ["Light Blue"],
    rating: 4.5,
    reviews: 0,
    description: "Fresh and versatile, these light blue stretch denim jeans are a wardrobe essential. Crafted from premium Cotton Lycra for a comfortable fit that looks great with everything.",
    material: "Cotton",
    pattern: "Solid",
    colour: "Light Blue",
    riseStyle: "Mid Rise",
    ageRange: "Kid",
    inStock: true,
  },
];
